<?php

namespace UserBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Security\Core\Encoder\BCryptPasswordEncoder;

/**
 * RequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

    public function getSalt()
    {
        return base_convert(sha1(uniqid(mt_rand(), true)), 16, 36);
    }

    public function encodePassword($password, $salt)
    {
        $encoder = new BCryptPasswordEncoder(8);

        return $encoder->encodePassword($password, $salt);
    }

    public function veryPassword($encoded, $raw, $salt)
    {
        $encoder = new BCryptPasswordEncoder(8);
        return $encoder->isPasswordValid($encoded, $raw, $salt);
    }
}
